month-1/week-5/task-5/loan_tracker/loan_tracker/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('loans.urls'))
]

month-1/week-5/task-5/loan_tracker/loans/urls.py
from django.urls import path
from .views import LoanListView, LoanUpdateView, LoanCreateView, LoanDeleteView
app_name = 'loans'

urlpatterns = [
  path('', LoanListView.as_view(), name='loan-list'),
  path('add/', LoanCreateView.as_view(), name='loan-add'),
  path('<int:pk>/edit/', LoanUpdateView.as_view(), name='loan-edit'),
  path('<int:pk>/delete/', LoanDeleteView.as_view(), name='loan-delete')
]

month-1/week-5/task-5/loan_tracker/loans/models.py
from django.db import models


# Create your models here.
class Loan(models.Model):
  name = models.CharField(max_length=250)
  amount = models.DecimalField(max_digits=10, decimal_places=2)
  created = models.DateTimeField(auto_now_add=True)
  date = models.DateField()
  reason = models.TextField()

  def __str__(self):
    return f"{self.name} - {self.amount}"

month-1/week-5/task-5/loan_tracker/loans/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from loans.models import Loan
from django.db.models import Q

# Create your views here.
class LoanListView(ListView):
  model = Loan
  template_name = 'loans/loans_list.html'
  context_object_name = 'loans'

  def get_queryset(self):
    queryset = super().get_queryset()
    query = self.request.GET.get('q', '')

    if query:
      queryset = queryset.filter(Q(name__icontains=query))
    return queryset


class LoanCreateView(CreateView):
  model = Loan
  template_name = 'loans/loans_form.html'
  fields = ['name', 'amount', 'date', 'reason']
  success_url = reverse_lazy('loans:loan-list')


class LoanUpdateView(UpdateView):
  model = Loan
  template_name = 'loans/loans_form.html'
  fields = ['name', 'amount', 'date', 'reason']
  success_url = reverse_lazy('loans:loan-list')

class LoanDeleteView(DeleteView):
  model = Loan
  template_name = 'loans/loans_confirm_delete.html'
  success_url = reverse_lazy('loans:loan-list')

month-1/week-5/task-5/loan_tracker/loans/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'loans/styles.css' %}">
  <title>{% block title %}Loan Tracker{% endblock %}</title>
</head>
<body>
  <header>
    <nav>
      <ul>
        <li><a href="{% url 'loans:loan-list' %}">Home</a></li>
        <li><a href="{% url 'loans:loan-add' %}">Add loan</a></li>
      </ul>
    </nav>
  </header>
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

month-1/week-5/task-5/loan_tracker/loans/templates/loans/loans_confirm_delete.html
{% extends 'base.html' %}

{% block title %}Delete Loan{% endblock %}

{% block content %}
  <main class="confirm-delete">
    <h2>Are you sure you want to delete this loan?</h2>
    <p><strong>{{ loan.name }}</strong>: ${{ loan.amount }} - {{ loan.date }}</p>

    <form method="post">
      {% csrf_token %}
      <button type="submit" class="delete">Yes, Delete</button>
    </form>

    <a href="{% url 'loans:loan-list' %}" class="cancel">Cancel</a>
  </main>
{% endblock %}

month-1/week-5/task-5/loan_tracker/loans/templates/loans/loans_form.html
{% extends 'base.html' %}

{% block title %}Add/Edit Loan{% endblock %}

{% block content %}
  <h2>{% if form.instance.pk %}Edit Loan{% else %}Add Loan{% endif %}</h2>

  <form method="post" action="{% if form.instance.pk %}{% url 'loans:loan-edit' form.instance.pk %}{% else %}{% url 'loans:loan-add' %}{% endif %}">
    {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Save</button>
  </form>

  <a href="{% url 'loans:loan-list' %}">Cancel</a>
  {% endblock %}

month-1/week-5/task-5/loan_tracker/loans/templates/loans/loans_list.html
{% extends 'base.html' %}

{% block title %} Loans List {% endblock %}

{% block content %}
  <h2>Loan List</h2>
  <div class="search-container">
    <form action="{% url 'loans:loan-list' %}" method="get">
      <input type="text" name="q" value="{{ request.GET.q }}" placeholder="search by loan name">
    </form>
  </div>

  <ul>
    {% for loan in loans %}
      <li>
        <div>
          <strong>{{ loan.name }}</strong> <br>
          <span class="amount">${{ loan.amount }}</span> - 
          <span class="date">{{ loan.date }}</span>
        </div>
        <div>
          <a href="{% url 'loans:loan-edit' loan.pk %}">Edit</a>
          <a class="delete" href="{% url 'loans:loan-delete' loan.pk %}">Delete</a>
        </div>
      </li>
    {% endfor %}
  </ul>

  <a href="{% url 'loans:loan-add' %}" class="button">Add Loan</a>
{% endblock %}